backend:
  name: github
  repo: <USER>/<REPO>
  branch: main
  base_url: https://decap-oauth.acronomi65.workers.dev/
  auth_endpoint: /api/auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
